### PR TITLE
Added a Creative Commons BY-SA Badge 

### PR DESCRIPTION
**Pull request by ArkhamCookie**
I saw you have Creative Commons 0, Creative Commons BY-ND, Creative Commons BY, Creative Commons NC-SA, Creative Commons NC, and Creative Commons SA, so it seems like a good addition.

### CODE REVIEW

**Comment by ArkhamCookie** [comment]
*Err...* I don't **think** those checks are related to me, but apologies if I missed something.

**Comment by ArkhamCookie** [comment]
[![forthebadge](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIyNjcuMjMiIGhlaWdodD0iMzUiIHZpZXdCb3g9IjAgMCAyNjcuMjMgMzUiPjxyZWN0IGNsYXNzPSJzdmdfX3JlY3QiIHg9IjAiIHk9IjAiIHdpZHRoPSIxOTAuNTcwMDAwMDAwMDAwMDIiIGhlaWdodD0iMzUiIGZpbGw9IiNCMEFFQUYiLz48cmVjdCBjbGFzcz0ic3ZnX19yZWN0IiB4PSIxODguNTcwMDAwMDAwMDAwMDIiIHk9IjAiIHdpZHRoPSI3OC42NiIgaGVpZ2h0PSIzNSIgZmlsbD0iIzFDMUMxRCIvPjxwYXRoIGNsYXNzPSJzdmdfX3RleHQiIGQ9Ik0xMy45NSAxOC4xOUwxMy45NSAxOC4xOUwxMy45NSAxNy4zOVExMy45NSAxNi4xOSAxNC4zOCAxNS4yN1ExNC44MCAxNC4zNSAxNS42MCAxMy44NVExNi40MCAxMy4zNSAxNy40NSAxMy4zNUwxNy40NSAxMy4zNVExOC44NiAxMy4zNSAxOS43MyAxNC4xMlEyMC41OSAxNC44OSAyMC43MyAxNi4yOUwyMC43MyAxNi4yOUwxOS4yNSAxNi4yOVExOS4xNCAxNS4zNyAxOC43MSAxNC45NlExOC4yOCAxNC41NSAxNy40NSAxNC41NUwxNy40NSAxNC41NVExNi40OCAxNC41NSAxNS45NyAxNS4yNlExNS40NSAxNS45NiAxNS40NCAxNy4zM0wxNS40NCAxNy4zM0wxNS40NCAxOC4wOVExNS40NCAxOS40NyAxNS45MyAyMC4yMFExNi40MyAyMC45MiAxNy4zOCAyMC45MkwxNy4zOCAyMC45MlExOC4yNSAyMC45MiAxOC42OSAyMC41M1ExOS4xMyAyMC4xNCAxOS4yNSAxOS4yMkwxOS4yNSAxOS4yMkwyMC43MyAxOS4yMlEyMC42MCAyMC41OSAxOS43MiAyMS4zNVExOC44NCAyMi4xMiAxNy4zOCAyMi4xMkwxNy4zOCAyMi4xMlExNi4zNiAyMi4xMiAxNS41OSAyMS42M1ExNC44MSAyMS4xNSAxNC4zOSAyMC4yNlExMy45NyAxOS4zNyAxMy45NSAxOC4xOVpNMjYuNTIgMjJMMjUuMDQgMjJMMjUuMDQgMTMuNDdMMjguMDQgMTMuNDdRMjkuNTIgMTMuNDcgMzAuMzIgMTQuMTNRMzEuMTIgMTQuNzkgMzEuMTIgMTYuMDVMMzEuMTIgMTYuMDVRMzEuMTIgMTYuOTAgMzAuNzEgMTcuNDhRMzAuMzAgMTguMDYgMjkuNTYgMTguMzdMMjkuNTYgMTguMzdMMzEuNDcgMjEuOTJMMzEuNDcgMjJMMjkuODkgMjJMMjguMTcgMTguNzFMMjYuNTIgMTguNzFMMjYuNTIgMjJaTTI2LjUyIDE0LjY2TDI2LjUyIDE3LjUyTDI4LjA1IDE3LjUyUTI4LjgwIDE3LjUyIDI5LjIyIDE3LjE1UTI5LjY0IDE2Ljc3IDI5LjY0IDE2LjExTDI5LjY0IDE2LjExUTI5LjY0IDE1LjQzIDI5LjI1IDE1LjA1UTI4Ljg2IDE0LjY4IDI4LjA5IDE0LjY2TDI4LjA5IDE0LjY2TDI2LjUyIDE0LjY2Wk00MS4wOSAyMkwzNS41MiAyMkwzNS41MiAxMy40N0w0MS4wNSAxMy40N0w0MS4wNSAxNC42NkwzNy4wMCAxNC42NkwzNy4wMCAxNy4wMkw0MC41MCAxNy4wMkw0MC41MCAxOC4xOUwzNy4wMCAxOC4xOUwzNy4wMCAyMC44Mkw0MS4wOSAyMC44Mkw0MS4wOSAyMlpNNDYuMDcgMjJMNDQuNTMgMjJMNDcuNzUgMTMuNDdMNDkuMDggMTMuNDdMNTIuMzEgMjJMNTAuNzYgMjJMNTAuMDYgMjAuMDFMNDYuNzYgMjAuMDFMNDYuMDcgMjJaTTQ4LjQxIDE1LjI4TDQ3LjE4IDE4LjgyTDQ5LjY1IDE4LjgyTDQ4LjQxIDE1LjI4Wk01Ny45NSAxNC42Nkw1NS4zMSAxNC42Nkw1NS4zMSAxMy40N0w2Mi4wOCAxMy40N0w2Mi4wOCAxNC42Nkw1OS40MiAxNC42Nkw1OS40MiAyMkw1Ny45NSAyMkw1Ny45NSAxNC42NlpNNjcuNDAgMjJMNjUuOTIgMjJMNjUuOTIgMTMuNDdMNjcuNDAgMTMuNDdMNjcuNDAgMjJaTTc0LjUwIDIyTDcxLjQ1IDEzLjQ3TDczLjA3IDEzLjQ3TDc1LjIxIDIwLjE0TDc3LjM4IDEzLjQ3TDc5LjAxIDEzLjQ3TDc1Ljk0IDIyTDc0LjUwIDIyWk04OC41NCAyMkw4Mi45NiAyMkw4Mi45NiAxMy40N0w4OC41MCAxMy40N0w4OC41MCAxNC42Nkw4NC40NCAxNC42Nkw4NC40NCAxNy4wMkw4Ny45NSAxNy4wMkw4Ny45NSAxOC4xOUw4NC40NCAxOC4xOUw4NC40NCAyMC44Mkw4OC41NCAyMC44Mkw4OC41NCAyMlpNOTguNDQgMTguMTlMOTguNDQgMTguMTlMOTguNDQgMTcuMzlROTguNDQgMTYuMTkgOTguODcgMTUuMjdROTkuMzAgMTQuMzUgMTAwLjEwIDEzLjg1UTEwMC44OSAxMy4zNSAxMDEuOTQgMTMuMzVMMTAxLjk0IDEzLjM1UTEwMy4zNiAxMy4zNSAxMDQuMjIgMTQuMTJRMTA1LjA4IDE0Ljg5IDEwNS4yMiAxNi4yOUwxMDUuMjIgMTYuMjlMMTAzLjc0IDE2LjI5UTEwMy42NCAxNS4zNyAxMDMuMjEgMTQuOTZRMTAyLjc4IDE0LjU1IDEwMS45NCAxNC41NUwxMDEuOTQgMTQuNTVRMTAwLjk4IDE0LjU1IDEwMC40NiAxNS4yNlE5OS45NCAxNS45NiA5OS45MyAxNy4zM0w5OS45MyAxNy4zM0w5OS45MyAxOC4wOVE5OS45MyAxOS40NyAxMDAuNDIgMjAuMjBRMTAwLjkyIDIwLjkyIDEwMS44NyAyMC45MkwxMDEuODcgMjAuOTJRMTAyLjc1IDIwLjkyIDEwMy4xOSAyMC41M1ExMDMuNjMgMjAuMTQgMTAzLjc0IDE5LjIyTDEwMy43NCAxOS4yMkwxMDUuMjIgMTkuMjJRMTA1LjA5IDIwLjU5IDEwNC4yMSAyMS4zNVExMDMuMzMgMjIuMTIgMTAxLjg3IDIyLjEyTDEwMS44NyAyMi4xMlExMDAuODUgMjIuMTIgMTAwLjA4IDIxLjYzUTk5LjMwIDIxLjE1IDk4Ljg4IDIwLjI2UTk4LjQ2IDE5LjM3IDk4LjQ0IDE4LjE5Wk0xMDkuMjYgMTguMDBMMTA5LjI2IDE4LjAwTDEwOS4yNiAxNy41MlExMDkuMjYgMTYuMjggMTA5LjcwIDE1LjMyUTExMC4xNSAxNC4zNyAxMTAuOTUgMTMuODZRMTExLjc2IDEzLjM1IDExMi44MCAxMy4zNVExMTMuODQgMTMuMzUgMTE0LjY1IDEzLjg1UTExNS40NiAxNC4zNSAxMTUuODkgMTUuMjlRMTE2LjMzIDE2LjIzIDExNi4zNCAxNy40OEwxMTYuMzQgMTcuNDhMMTE2LjM0IDE3Ljk2UTExNi4zNCAxOS4yMSAxMTUuOTEgMjAuMTZRMTE1LjQ3IDIxLjEwIDExNC42NyAyMS42MVExMTMuODYgMjIuMTIgMTEyLjgxIDIyLjEyTDExMi44MSAyMi4xMlExMTEuNzggMjIuMTIgMTEwLjk2IDIxLjYxUTExMC4xNSAyMS4xMCAxMDkuNzEgMjAuMTdRMTA5LjI3IDE5LjIzIDEwOS4yNiAxOC4wMFpNMTEwLjc0IDE3LjQ2TDExMC43NCAxNy45NlExMTAuNzQgMTkuMzYgMTExLjI5IDIwLjEzUTExMS44NCAyMC45MCAxMTIuODEgMjAuOTBMMTEyLjgxIDIwLjkwUTExMy44MCAyMC45MCAxMTQuMzMgMjAuMTVRMTE0Ljg2IDE5LjQwIDExNC44NiAxNy45NkwxMTQuODYgMTcuOTZMMTE0Ljg2IDE3LjUxUTExNC44NiAxNi4wOSAxMTQuMzIgMTUuMzRRMTEzLjc5IDE0LjU4IDExMi44MCAxNC41OEwxMTIuODAgMTQuNThRMTExLjg0IDE0LjU4IDExMS4zMCAxNS4zM1ExMTAuNzYgMTYuMDkgMTEwLjc0IDE3LjQ2TDExMC43NCAxNy40NlpNMTIyLjI4IDIyTDEyMC44MSAyMkwxMjAuODEgMTMuNDdMMTIyLjczIDEzLjQ3TDEyNS4xOSAyMC4wMUwxMjcuNjQgMTMuNDdMMTI5LjU2IDEzLjQ3TDEyOS41NiAyMkwxMjguMDggMjJMMTI4LjA4IDE5LjE5TDEyOC4yMyAxNS40M0wxMjUuNzEgMjJMMTI0LjY1IDIyTDEyMi4xNCAxNS40M0wxMjIuMjggMTkuMTlMMTIyLjI4IDIyWk0xMzUuNzggMjJMMTM0LjMwIDIyTDEzNC4zMCAxMy40N0wxMzYuMjIgMTMuNDdMMTM4LjY4IDIwLjAxTDE0MS4xNCAxMy40N0wxNDMuMDUgMTMuNDdMMTQzLjA1IDIyTDE0MS41OCAyMkwxNDEuNTggMTkuMTlMMTQxLjcyIDE1LjQzTDEzOS4yMCAyMkwxMzguMTQgMjJMMTM1LjYzIDE1LjQzTDEzNS43OCAxOS4xOUwxMzUuNzggMjJaTTE0Ny41MiAxOC4wMEwxNDcuNTIgMTguMDBMMTQ3LjUyIDE3LjUyUTE0Ny41MiAxNi4yOCAxNDcuOTcgMTUuMzJRMTQ4LjQxIDE0LjM3IDE0OS4yMSAxMy44NlExNTAuMDIgMTMuMzUgMTUxLjA2IDEzLjM1UTE1Mi4xMSAxMy4zNSAxNTIuOTEgMTMuODVRMTUzLjcyIDE0LjM1IDE1NC4xNiAxNS4yOVExNTQuNjAgMTYuMjMgMTU0LjYwIDE3LjQ4TDE1NC42MCAxNy40OEwxNTQuNjAgMTcuOTZRMTU0LjYwIDE5LjIxIDE1NC4xNyAyMC4xNlExNTMuNzMgMjEuMTAgMTUyLjkzIDIxLjYxUTE1Mi4xMiAyMi4xMiAxNTEuMDcgMjIuMTJMMTUxLjA3IDIyLjEyUTE1MC4wNCAyMi4xMiAxNDkuMjMgMjEuNjFRMTQ4LjQxIDIxLjEwIDE0Ny45NyAyMC4xN1ExNDcuNTMgMTkuMjMgMTQ3LjUyIDE4LjAwWk0xNDkuMDEgMTcuNDZMMTQ5LjAxIDE3Ljk2UTE0OS4wMSAxOS4zNiAxNDkuNTUgMjAuMTNRMTUwLjEwIDIwLjkwIDE1MS4wNyAyMC45MEwxNTEuMDcgMjAuOTBRMTUyLjA2IDIwLjkwIDE1Mi41OSAyMC4xNVExNTMuMTIgMTkuNDAgMTUzLjEyIDE3Ljk2TDE1My4xMiAxNy45NkwxNTMuMTIgMTcuNTFRMTUzLjEyIDE2LjA5IDE1Mi41OCAxNS4zNFExNTIuMDUgMTQuNTggMTUxLjA2IDE0LjU4TDE1MS4wNiAxNC41OFExNTAuMTAgMTQuNTggMTQ5LjU2IDE1LjMzUTE0OS4wMiAxNi4wOSAxNDkuMDEgMTcuNDZMMTQ5LjAxIDE3LjQ2Wk0xNjAuNTUgMjJMMTU5LjA3IDIyTDE1OS4wNyAxMy40N0wxNjAuNTUgMTMuNDdMMTY0LjM2IDE5LjU0TDE2NC4zNiAxMy40N0wxNjUuODMgMTMuNDdMMTY1LjgzIDIyTDE2NC4zNSAyMkwxNjAuNTUgMTUuOTVMMTYwLjU1IDIyWk0xNzAuMTQgMTkuNDJMMTcwLjE0IDE5LjQyTDE3MS42MiAxOS40MlExNzEuNjIgMjAuMTUgMTcyLjEwIDIwLjU1UTE3Mi41OCAyMC45NSAxNzMuNDggMjAuOTVMMTczLjQ4IDIwLjk1UTE3NC4yNSAyMC45NSAxNzQuNjQgMjAuNjNRMTc1LjAzIDIwLjMyIDE3NS4wMyAxOS44MEwxNzUuMDMgMTkuODBRMTc1LjAzIDE5LjI0IDE3NC42NCAxOC45NFExNzQuMjQgMTguNjMgMTczLjIxIDE4LjMyUTE3Mi4xOCAxOC4wMSAxNzEuNTcgMTcuNjNMMTcxLjU3IDE3LjYzUTE3MC40MCAxNi45MCAxNzAuNDAgMTUuNzJMMTcwLjQwIDE1LjcyUTE3MC40MCAxNC42OSAxNzEuMjUgMTQuMDJRMTcyLjA5IDEzLjM1IDE3My40MyAxMy4zNUwxNzMuNDMgMTMuMzVRMTc0LjMyIDEzLjM1IDE3NS4wMiAxMy42OFExNzUuNzEgMTQuMDEgMTc2LjExIDE0LjYxUTE3Ni41MSAxNS4yMiAxNzYuNTEgMTUuOTZMMTc2LjUxIDE1Ljk2TDE3NS4wMyAxNS45NlExNzUuMDMgMTUuMjkgMTc0LjYxIDE0LjkxUTE3NC4yMCAxNC41NCAxNzMuNDIgMTQuNTRMMTczLjQyIDE0LjU0UTE3Mi42OSAxNC41NCAxNzIuMjkgMTQuODVRMTcxLjg5IDE1LjE2IDE3MS44OSAxNS43MUwxNzEuODkgMTUuNzFRMTcxLjg5IDE2LjE4IDE3Mi4zMiAxNi41MFExNzIuNzUgMTYuODEgMTczLjc1IDE3LjEwUTE3NC43NSAxNy40MCAxNzUuMzUgMTcuNzhRMTc1Ljk1IDE4LjE2IDE3Ni4yMyAxOC42NVExNzYuNTIgMTkuMTMgMTc2LjUyIDE5Ljc5TDE3Ni41MiAxOS43OVExNzYuNTIgMjAuODYgMTc1LjcwIDIxLjQ5UTE3NC44OCAyMi4xMiAxNzMuNDggMjIuMTJMMTczLjQ4IDIyLjEyUTE3Mi41NiAyMi4xMiAxNzEuNzggMjEuNzdRMTcxLjAwIDIxLjQzIDE3MC41NyAyMC44M1ExNzAuMTQgMjAuMjIgMTcwLjE0IDE5LjQyWiIgZmlsbD0iI0ZGRkZGRiIvPjxwYXRoIGNsYXNzPSJzdmdfX3RleHQiIGQ9Ik0yMDcuMzAgMjJMMjAyLjc2IDIyTDIwMi43NiAxMy42MEwyMDcuMDYgMTMuNjBRMjA4LjY2IDEzLjYwIDIwOS41MCAxNC4xOVEyMTAuMzUgMTQuNzkgMjEwLjM1IDE1Ljc5TDIxMC4zNSAxNS43OVEyMTAuMzUgMTYuMzkgMjEwLjA1IDE2Ljg3UTIwOS43NSAxNy4zNCAyMDkuMjEgMTcuNjJMMjA5LjIxIDE3LjYyUTIwOS45NCAxNy44NyAyMTAuMzQgMTguNDFRMjEwLjc1IDE4Ljk0IDIxMC43NSAxOS43MEwyMTAuNzUgMTkuNzBRMjEwLjc1IDIwLjgwIDIwOS44NiAyMS40MFEyMDguOTcgMjIgMjA3LjMwIDIyTDIwNy4zMCAyMlpNMjA1LjExIDE4LjU4TDIwNS4xMSAyMC4yOEwyMDcuMTEgMjAuMjhRMjA4LjM1IDIwLjI4IDIwOC4zNSAxOS40M0wyMDguMzUgMTkuNDNRMjA4LjM1IDE4LjU4IDIwNy4xMSAxOC41OEwyMDcuMTEgMTguNThMMjA1LjExIDE4LjU4Wk0yMDUuMTEgMTUuMzFMMjA1LjExIDE2Ljk0TDIwNi43NCAxNi45NFEyMDcuOTQgMTYuOTQgMjA3Ljk0IDE2LjEyTDIwNy45NCAxNi4xMlEyMDcuOTQgMTUuMzEgMjA2Ljc0IDE1LjMxTDIwNi43NCAxNS4zMUwyMDUuMTEgMTUuMzFaTTIxNy41OSAxOC45NUwyMTQuMzkgMTMuNjBMMjE2LjkwIDEzLjYwTDIxOC44OSAxNi45NEwyMjAuODggMTMuNjBMMjIzLjE4IDEzLjYwTDIxOS45NyAxOC45OUwyMTkuOTcgMjJMMjE3LjU5IDIyTDIxNy41OSAxOC45NVpNMjMwLjUxIDE5LjQ2TDIyNy4wMCAxOS40NkwyMjcuMDAgMTcuNzFMMjMwLjUxIDE3LjcxTDIzMC41MSAxOS40NlpNMjM0LjgyIDIxLjI0TDIzNC44MiAyMS4yNEwyMzUuNjAgMTkuNDlRMjM2LjE2IDE5Ljg2IDIzNi45MSAyMC4wOVEyMzcuNjUgMjAuMzIgMjM4LjM3IDIwLjMyTDIzOC4zNyAyMC4zMlEyMzkuNzQgMjAuMzIgMjM5Ljc0IDE5LjY0TDIzOS43NCAxOS42NFEyMzkuNzQgMTkuMjggMjM5LjM1IDE5LjExUTIzOC45NiAxOC45MyAyMzguMTAgMTguNzRMMjM4LjEwIDE4Ljc0UTIzNy4xNSAxOC41MyAyMzYuNTEgMTguMzBRMjM1Ljg4IDE4LjA2IDIzNS40MiAxNy41NVEyMzQuOTcgMTcuMDMgMjM0Ljk3IDE2LjE2TDIzNC45NyAxNi4xNlEyMzQuOTcgMTUuMzkgMjM1LjM5IDE0Ljc3UTIzNS44MCAxNC4xNSAyMzYuNjQgMTMuNzlRMjM3LjQ3IDEzLjQzIDIzOC42OCAxMy40M0wyMzguNjggMTMuNDNRMjM5LjUxIDEzLjQzIDI0MC4zMSAxMy42MlEyNDEuMTIgMTMuODAgMjQxLjczIDE0LjE3TDI0MS43MyAxNC4xN0wyNDEuMDAgMTUuOTNRMjM5LjgwIDE1LjI4IDIzOC42NyAxNS4yOEwyMzguNjcgMTUuMjhRMjM3Ljk2IDE1LjI4IDIzNy42NCAxNS40OVEyMzcuMzIgMTUuNzAgMjM3LjMyIDE2LjA0TDIzNy4zMiAxNi4wNFEyMzcuMzIgMTYuMzcgMjM3LjcwIDE2LjU0UTIzOC4wOCAxNi43MSAyMzguOTMgMTYuODlMMjM4LjkzIDE2Ljg5UTIzOS44OSAxNy4xMCAyNDAuNTIgMTcuMzNRMjQxLjE1IDE3LjU2IDI0MS42MiAxOC4wN1EyNDIuMDggMTguNTggMjQyLjA4IDE5LjQ2TDI0Mi4wOCAxOS40NlEyNDIuMDggMjAuMjEgMjQxLjY2IDIwLjgzUTI0MS4yNCAyMS40NCAyNDAuNDAgMjEuODBRMjM5LjU2IDIyLjE3IDIzOC4zNiAyMi4xN0wyMzguMzYgMjIuMTdRMjM3LjM0IDIyLjE3IDIzNi4zOCAyMS45MlEyMzUuNDIgMjEuNjcgMjM0LjgyIDIxLjI0Wk0yNDguMDcgMjJMMjQ1LjY1IDIyTDI0OS4zNiAxMy42MEwyNTEuNzAgMTMuNjBMMjU1LjQyIDIyTDI1Mi45NSAyMkwyNTIuMjkgMjAuMzdMMjQ4Ljc0IDIwLjM3TDI0OC4wNyAyMlpNMjUwLjUxIDE1LjkzTDI0OS40MyAxOC42MUwyNTEuNTkgMTguNjFMMjUwLjUxIDE1LjkzWiIgZmlsbD0iI0ZGRkZGRiIgeD0iMjAxLjU3MDAwMDAwMDAwMDAyIi8+PC9zdmc+)](https://forthebadge.com)

Here is the [link](https://forthebadge.com/generator/?plabel=CREATIVE+COMMONS&pbg=%23B0AEAF&sbg=%231C1C1D&slabel=BY-SA) to the badge generator page and the markdown.

**Comment by ArkhamCookie** [comment]
cc-by-sa
Here's a view of the badge (using https://raw.githubusercontent.com/)
I also changed the filename to be uniform with the other creative commons.

**Comment by ArkhamCookie** [comment]
cc-by-sa
Here's a view of the badge (using https://raw.githubusercontent.com/)
I also changed the filename to be uniform with the other creative commons.

**Comment by p6afernandes** [comment]
Hey @ArkhamCookie 

Thanks for your PR and sorry for the delay. My team and I have taken over the project as of September 2023 and all support and upkeep related to this project has been transferred. Check out our new [FAQ ](https://forthebadge.com/#/faq)on the site for more info on this!

**In the meantime, Your badge has been added to the site:** https://forthebadge.com/images/badges/cc-by.svg

Badge on!

**Pull request closed without merging**
